name: drag_select_grid_view
description: A new Flutter package.
version: 0.0.1
author: Hugo Passos
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.14.11

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter

flutter:
