name: drag_select_grid_view
description: Grid that supports both dragging and tapping to select its items.
version: 0.1.0
author: Hugo Passos <hugocbpassos@gmail.com>
homepage: https://github.com/hugocbpassos/drag_select_grid_view/
issue_tracker: https://github.com/hugocbpassos/drag_select_grid_view/issues

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.14.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  meta: ^1.1.7